export const profileFields = [
  "artist",
  "city",
  "styles",
  "textMini",
  "textLong",
  "textStudio",
  "visitRules",
  "openDates",
  "website",
  "instagram",
  "events",
  "eventsContact",
  // "address",
  // "directions",
  "accountType",
  "published",
  "studio_id",
];
