export const studioColumns = [
  "artist",
  "location",
  "district",
  "styles",
  "textMini",
  "textLong",
  "textStudio",
  "visitRules",
  "openDates",
  "availability",
  "languages",
  "website",
  "instagram",
  "eventId",
  //TODO: remove
  "events",
  "eventsContact",
  "eventsLink",
  // Till here
  "referrals",
  // "address",
  // "directions",
  "accountType",
  "published",
  "studio_id",
];
